layout_spectrum: 0.3659705375864327
typography_spectrum: 0.03797508580674703
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.6598128504105982
  lightness: 0.8439572385301131
  saturation: 0.9381364660878841
  rhythmicContrast: 0.7055047028264639
name: machine
favicon: null
title: welcome to the machine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
content: []
description: spontaneous filth from outside the bubble
url: 'https://giv.me'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/77429ac2-a4f6-4a15-af86-accde3eaa7e5.png
author:
  name: Dog
  email: info@giv.me
github: true
